env:
  global:
    - CODECOV_TOKEN="240b0e8b-e300-4087-9833-6fade7c9423a" # https://codecov.io

language: node_js

node_js:
  - 10

before_script:
  - npm install -g codecov

script:
  - npm run coverage # get the coverage run before building
  - codecov          # upload coverage reports to codecov.io
  - npm run build    # we have a build badge, so run the build
